### ISSUE TITLE
Help: My wallet stopped working

### ISSUE THREAD

**Issue by 0xTwicer** [namecoin/electrum-nmc#332]
When i try to renew a name, this message appears:
'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

When i try to register a name or transfer a name, this message appears:
Sorry! something went wrong while executing Electrum-NMC

What can i do? I have names expiring in three days which i need to renew.

**Comment by JeremyRand** [comment]
> When i try to renew a name, this message appears:
'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

I think this is fixed in the `master-4.0.6` branch, which will be released soon (though probably not in the next 3 days).  If you trust Cirrus binaries (there's not really any reason that you should), you can find them at https://github.com/namecoin/electrum-nmc/runs/8462859340 (choose your OS on the left side, then click "View more details on Cirrus CI", then find the download under Artifacts).  Make sure you back up your wallet (and preferably your entire Electrum-NMC profile folder) if you try those binaries though.  Otherwise, I *think* you can work around it with your current version by running the following from the console: `name_update('d/whatever_name_you_want_to_renew', value='new_value_for_that_name')`.  It should return a hex transaction, take that, and run `broadcast('hex_tx_goes_here')`, which will broadcast the renewal.

(If you want lower-latency tech support, IRC/Matrix might be helpful: https://www.namecoin.org/resources/chat/ .)

**Comment by JeremyRand** [comment]
Any luck?

**Comment by 0xTwicer** [comment]
Hi Jeremy,
Thanks for asking, I found a solution :)
My Electrum wallet had some type of bug, so I exported the private keys to
a Namecoin Core wallet. It worked and could renew my assets.

**Comment by JeremyRand** [comment]
OK great, good to hear you got things renewed.  FYI I believe this bug only shows up if you have some names in your wallet with non-ASCII encoding.  Should be fixed in the next release.

**Comment by 0xTwicer** [comment]
Good to know. I also keep most of my assets in an other electrum wallet.
Thanks!

**Comment by JeremyRand** [comment]
Closing this issue since OP has worked around it, and the underlying bug is fixed in `master-4.0.6` branch.  Please don't hesitate to open a new issue if you run into problems again, thanks!
